// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApZbp-Oz5GINYW2OL7es7kcsX6BJpI7Dc',
    appId: '1:409116633721:web:ea5da2a39b6aae325f82a8',
    messagingSenderId: '409116633721',
    projectId: 'finalproject-90c0e',
    authDomain: 'finalproject-90c0e.firebaseapp.com',
    storageBucket: 'finalproject-90c0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1clDBINf4YZzJiTii2S7VE9m2UbhFQLw',
    appId: '1:409116633721:android:d2f97fd31f5a0d725f82a8',
    messagingSenderId: '409116633721',
    projectId: 'finalproject-90c0e',
    storageBucket: 'finalproject-90c0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWWYmO89z7I_GoMmbOOonWqlsqT5hzW1g',
    appId: '1:409116633721:ios:2b5d53fc9e4f55805f82a8',
    messagingSenderId: '409116633721',
    projectId: 'finalproject-90c0e',
    storageBucket: 'finalproject-90c0e.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWWYmO89z7I_GoMmbOOonWqlsqT5hzW1g',
    appId: '1:409116633721:ios:2b5d53fc9e4f55805f82a8',
    messagingSenderId: '409116633721',
    projectId: 'finalproject-90c0e',
    storageBucket: 'finalproject-90c0e.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApZbp-Oz5GINYW2OL7es7kcsX6BJpI7Dc',
    appId: '1:409116633721:web:7f2720f71cddd6425f82a8',
    messagingSenderId: '409116633721',
    projectId: 'finalproject-90c0e',
    authDomain: 'finalproject-90c0e.firebaseapp.com',
    storageBucket: 'finalproject-90c0e.appspot.com',
  );

}